services:
  - type: web
    name: sclshi
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_REMOTE_DB
        value: "1"
      - key: CLIENT_URL
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: POPUP_TAB_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: APPS_SCRIPT_URL
        sync: false
