import { useRef, useState } from 'react'
import BetController from '../components/BetController'
import GameShell from '../components/GameShell'
import { useCasinoWallet } from '../wallet'

function outcome(){return Math.max(1,Math.floor((.99/(1-Math.random()))*100)/100)}
export default function Limbo({onBack}:{onBack:()=>void}){
 const {debit,credit,balance}=useCasinoWallet();const [amount,setAmount]=useState(10);const [target,setTarget]=useState(2);const [status,setStatus]=useState<'idle'|'locked'>('idle');const [value,setValue]=useState(1);const [result,setResult]=useState<'none'|'win'|'loss'>('none');const timer=useRef(0)
 const play=()=>{if(!debit(amount))return;setStatus('locked');setResult('none');let ticks=0;timer.current=window.setInterval(()=>{setValue(1+Math.random()*Math.max(5,target*1.4));if(++ticks>18){clearInterval(timer.current);const hit=outcome();setValue(hit);const win=hit>=target;setResult(win?'win':'loss');if(win)credit(amount*target);setStatus('idle')}},55)}
 const panel=<BetController amount={amount} setAmount={setAmount} status={status} onAction={play} disabled={amount>balance}><label className="block"><span className="mb-2 block text-xs font-semibold text-slate-400">Target multiplier</span><div className="flex items-center rounded-lg bg-[#0c1623] px-3"><input disabled={status!=='idle'} type="number" min="1.01" max="10000" step=".01" value={target} onChange={e=>setTarget(Math.min(10000,Math.max(1.01,Number(e.target.value))))} className="w-full bg-transparent py-3 font-bold outline-none"/><b className="text-slate-500">×</b></div></label><div className="flex justify-between rounded-lg bg-[#0c1623] p-3 text-xs"><span className="text-slate-400">Win chance</span><b>{Math.min(98.02,99/target).toFixed(2)}%</b></div></BetController>
 return <GameShell title="Limbo" onBack={onBack} panel={panel}><div className="text-center"><div className="mb-8 text-xs font-bold uppercase tracking-[.35em] text-slate-500">Multiplier result</div><div className={`ticker-glow font-display text-7xl font-extrabold tracking-tight sm:text-9xl ${result==='win'?'text-lime':result==='loss'?'text-red-400':'text-white'}`}>{value.toFixed(2)}×</div><div className={`mt-8 inline-flex rounded-full px-5 py-2 text-xs font-bold uppercase tracking-wider ${result==='win'?'bg-lime/10 text-lime':result==='loss'?'bg-red-400/10 text-red-400':'bg-white/5 text-slate-500'}`}>{result==='win'?`Target cleared · paid ${target.toFixed(2)}×`:result==='loss'?'Target missed':'Set your target and play'}</div></div></GameShell>
}
