import { useEffect, useRef, useState } from 'react'
import { Bomb, Gem } from 'lucide-react'
import BetController from '../components/BetController'
import GameShell from '../components/GameShell'
import ResultPopup, { RoundResult } from '../components/ResultPopup'
import { BetStatus } from '../types'
import { useCasinoWallet } from '../wallet'
import { postCasino } from '../casinoApi'
import NumericInput from '../components/NumericInput'

type MineCell={index:number;revealed:boolean;type:'mine'|'safe'|null}
type MinesState={status:string;mineCount:number;revealedSafeCount:number;currentMultiplier:number;potentialPayout:number;betAmount:number;board:MineCell[]}
type MinesResponse={state:MinesState;newBalance:number;hitMine?:boolean;payout?:number;profit?:number;multiplier?:number}

export default function Mines({onBack}:{onBack:()=>void}){
 const {syncBalance,balance,recordRound}=useCasinoWallet(); const [amount,setAmount]=useState(10);const [mineCount,setMineCount]=useState(3);const [mines,setMines]=useState<Set<number>>(new Set());const [revealed,setRevealed]=useState<Set<number>>(new Set());const [status,setStatus]=useState<BetStatus>('idle');const [lost,setLost]=useState(false);const [roundResult,setRoundResult]=useState<RoundResult|null>(null);const [multiplier,setMultiplier]=useState(1);const [potential,setPotential]=useState(0);const [controllerMode,setControllerMode]=useState<'manual'|'auto'>('manual');const [autoPicks,setAutoPicks]=useState<number[]>([]);const autoTimer=useRef(0);const resetTimer=useRef(0);const busy=useRef(false)
 const applyState=(state:MinesState)=>{setMineCount(state.mineCount);setMultiplier(state.currentMultiplier);setPotential(state.potentialPayout);setRevealed(new Set(state.board.filter(cell=>cell.revealed).map(cell=>cell.index)));setMines(new Set(state.board.filter(cell=>cell.type==='mine').map(cell=>cell.index)))}
 const start=async()=>{if(status!=='idle'||busy.current||amount>balance)return;busy.current=true;setStatus('locked');setRoundResult(null);setLost(false);try{const response=await postCasino<MinesResponse>('/mines/start',{betAmount:amount,mineCount});syncBalance(response.newBalance);applyState(response.state);setStatus('active')}catch(error){setRoundResult({profit:0,title:error instanceof Error?error.message:'Unable to start Mines',error:true});setStatus('idle')}finally{busy.current=false}}
 const settleCashout=(response:MinesResponse,title:string)=>{applyState(response.state);syncBalance(response.newBalance);setStatus('locked');const profit=Number(response.profit||0);recordRound(amount,profit);resetTimer.current=window.setTimeout(()=>{setMines(new Set());setRevealed(new Set());setLost(false);setMultiplier(1);setPotential(0);setRoundResult({profit,title});setStatus('idle')},800)}
 const revealTile=async(i:number)=>{if(busy.current)return null;busy.current=true;try{const response=await postCasino<MinesResponse>('/mines/reveal',{index:i});applyState(response.state);syncBalance(response.newBalance);if(response.hitMine){setLost(true);setStatus('idle');recordRound(amount,-amount);setRoundResult({profit:-amount})}return response}catch(error){setRoundResult({profit:0,title:error instanceof Error?error.message:'Unable to reveal tile',error:true});return null}finally{busy.current=false}}
 const click=(i:number)=>{if(controllerMode==='auto'){if(status==='idle')setAutoPicks(current=>current.includes(i)?current.filter(tile=>tile!==i):[...current,i]);return}if(status!=='active'||revealed.has(i))return;void revealTile(i)}
 const cashout=async()=>{if(status!=='active'||busy.current)return;busy.current=true;try{const response=await postCasino<MinesResponse>('/mines/cashout',{});settleCashout(response,'Cash-out profit')}catch(error){setRoundResult({profit:0,title:error instanceof Error?error.message:'Unable to cash out',error:true})}finally{busy.current=false}}
 const autoRound=async()=>{if(status!=='idle'||busy.current||amount>balance||autoPicks.length===0)return;busy.current=true;setStatus('locked');setRoundResult(null);setLost(false);try{const started=await postCasino<MinesResponse>('/mines/start',{betAmount:amount,mineCount});syncBalance(started.newBalance);applyState(started.state);setStatus('active')}catch(error){setRoundResult({profit:0,title:error instanceof Error?error.message:'Unable to start Mines',error:true});setStatus('idle');busy.current=false;return}busy.current=false;let pickIndex=0;const revealNext=async()=>{const response=await revealTile(autoPicks[pickIndex]);if(!response||response.hitMine)return;pickIndex+=1;if(pickIndex>=autoPicks.length){await cashout();return}autoTimer.current=window.setTimeout(()=>void revealNext(),350)};autoTimer.current=window.setTimeout(()=>void revealNext(),350)}
 useEffect(()=>()=>{clearTimeout(autoTimer.current);clearTimeout(resetTimer.current)},[])
 const panel=<BetController amount={amount} setAmount={setAmount} status={status} onAction={status==='active'?()=>void cashout():()=>void start()} onAutoAction={()=>void autoRound()} onModeChange={setControllerMode} autoDisabled={autoPicks.length===0} canCashOut={status==='active'} disabled={amount>balance} potential={potential} lastResult={roundResult}><label className="block"><span className="mb-2 block text-xs font-semibold text-slate-400">Mines</span><div className="mb-3 flex items-center rounded-lg border border-[#365267] bg-[#0c1623] px-3"><NumericInput aria-label="Number of mines" disabled={status!=='idle'} value={mineCount} onCommit={setMineCount} min={1} max={24} integer className="w-full bg-transparent py-3 font-bold outline-none"/><span className="text-xs font-bold text-slate-500">1–24</span></div><input aria-label="Mines slider" disabled={status!=='idle'} type="range" min="1" max="24" value={mineCount} onChange={e=>setMineCount(Number(e.target.value))} className="w-full accent-lime"/></label><div className="flex justify-between rounded-lg bg-[#0c1623] p-3 text-xs"><span className="text-slate-400">{controllerMode==='auto'?'Auto picks':'Diamonds'}</span><b>{controllerMode==='auto'?autoPicks.length:25-mineCount}</b></div></BetController>
 return <><GameShell title="Mines" onBack={onBack} panel={panel}><div className="w-full max-w-[590px]"><div className="mb-5 text-center"><div className={`font-display text-4xl font-extrabold ${lost?'text-red-400':'text-lime'}`}>{lost?'BOOM':status==='active'?`${multiplier.toFixed(2)}×`:status==='locked'?'BOARD REVEAL':controllerMode==='auto'?'Pick your auto tiles':'Choose your stake'}</div><div className="mt-1 text-xs text-slate-500">{status==='active'?'Find gems, then cash out before the mine.':status==='locked'?'Revealing the full board…':controllerMode==='auto'?'Select tiles in the order Auto Bet should reveal them each round.':'Configure mines and start a round.'}</div></div><div className="grid grid-cols-5 gap-2 sm:gap-3">{Array.from({length:25},(_,i)=>{const show=revealed.has(i),mine=mines.has(i),pickOrder=controllerMode==='auto'&&status==='idle'?autoPicks.indexOf(i):-1;return <button aria-label={`Tile ${i+1}${pickOrder>=0?`, auto pick ${pickOrder+1}`:''}`} key={i} onClick={()=>click(i)} className={`tile-shadow relative aspect-square rounded-lg transition active:translate-y-1 active:shadow-none ${status==='locked'&&show?'mine-reveal ':''}${show?(mine?'bg-red-500':'bg-lime'):pickOrder>=0?'bg-sky-500 ring-2 ring-sky-300':'bg-[#2a3b4e] hover:bg-[#344a60]'}`}>{show?(mine?<Bomb className="mx-auto text-white" size={30}/>:<Gem className="mx-auto text-slate-950" fill="currentColor" size={30}/>):pickOrder>=0?<span className="font-display text-xl font-extrabold text-white">{pickOrder+1}</span>:null}</button>})}</div>{controllerMode==='auto'&&status==='idle'?<div className="mt-4 flex items-center justify-between rounded-lg border border-sky-400/20 bg-sky-400/10 px-4 py-3 text-xs"><span className="text-sky-100">{autoPicks.length?`${autoPicks.length} tile${autoPicks.length===1?'':'s'} repeat every round`:'Choose at least one tile to start Auto Bet'}</span>{autoPicks.length?<button onClick={()=>setAutoPicks([])} className="font-bold text-sky-300 hover:text-white">Clear picks</button>:null}</div>:null}</div></GameShell><ResultPopup result={roundResult} onClose={()=>setRoundResult(null)}/></>
}
