import { useEffect, useRef, useState } from 'react'
import { Bomb, Gem } from 'lucide-react'
import BetController from '../components/BetController'
import GameShell from '../components/GameShell'
import ResultPopup, { RoundResult } from '../components/ResultPopup'
import { BetStatus } from '../types'
import { useCasinoWallet } from '../wallet'

export default function Mines({onBack}:{onBack:()=>void}){
 const {debit,credit,balance,recordRound}=useCasinoWallet(); const [amount,setAmount]=useState(10);const [mineCount,setMineCount]=useState(3);const [mines,setMines]=useState<Set<number>>(new Set());const [revealed,setRevealed]=useState<Set<number>>(new Set());const [status,setStatus]=useState<BetStatus>('idle');const [lost,setLost]=useState(false);const [roundResult,setRoundResult]=useState<RoundResult|null>(null);const autoTimer=useRef(0);const resetTimer=useRef(0)
 const multiplier=+(Math.pow(25/(25-mineCount),revealed.size)*.99).toFixed(2)
 const start=()=>{if(!debit(amount))return;setRoundResult(null);const next=new Set<number>();while(next.size<mineCount)next.add(Math.floor(Math.random()*25));setMines(next);setRevealed(new Set());setLost(false);setStatus('active')}
 const settleCashout=(payout:number,title:string)=>{const profit=payout-amount;credit(payout);recordRound(amount,profit);setStatus('locked');setRevealed(new Set(Array.from({length:25},(_,index)=>index)));resetTimer.current=window.setTimeout(()=>{setMines(new Set());setRevealed(new Set());setLost(false);setRoundResult({profit,title});setStatus('idle')},800)}
 const click=(i:number)=>{if(status!=='active'||revealed.has(i))return;if(mines.has(i)){setLost(true);setRevealed(new Set(Array.from({length:25},(_,n)=>n)));setStatus('idle');recordRound(amount,-amount);setRoundResult({profit:-amount})}else setRevealed(v=>new Set(v).add(i))}
 const cashout=()=>{if(status!=='active')return;settleCashout(Math.floor(amount*multiplier),'Cash-out profit')}
 const autoRound=()=>{if(!debit(amount))return;setRoundResult(null);const next=new Set<number>();while(next.size<mineCount)next.add(Math.floor(Math.random()*25));setMines(next);setRevealed(new Set());setLost(false);setStatus('active');const opened=new Set<number>();const target=Math.min(3,25-mineCount);const revealNext=()=>{let tile=Math.floor(Math.random()*25);while(opened.has(tile))tile=Math.floor(Math.random()*25);opened.add(tile);setRevealed(new Set(opened));if(next.has(tile)){setLost(true);setRevealed(new Set(Array.from({length:25},(_,index)=>index)));setStatus('idle');recordRound(amount,-amount);setRoundResult({profit:-amount});return}if(opened.size>=target){const autoMultiplier=+(Math.pow(25/(25-mineCount),opened.size)*.99).toFixed(2);settleCashout(Math.floor(amount*autoMultiplier),'Auto cash-out profit');return}autoTimer.current=window.setTimeout(revealNext,350)};autoTimer.current=window.setTimeout(revealNext,350)}
 useEffect(()=>()=>{clearTimeout(autoTimer.current);clearTimeout(resetTimer.current)},[])
 const panel=<BetController amount={amount} setAmount={setAmount} status={status} onAction={status==='active'?cashout:start} onAutoAction={autoRound} canCashOut={status==='active'} disabled={amount>balance} potential={amount*multiplier} lastResult={roundResult}><label className="block"><span className="mb-2 flex justify-between text-xs font-semibold text-slate-400"><span>Mines</span><span>{mineCount}</span></span><input disabled={status!=='idle'} type="range" min="1" max="24" value={mineCount} onChange={e=>setMineCount(Number(e.target.value))} className="w-full accent-lime"/></label><div className="flex justify-between rounded-lg bg-[#0c1623] p-3 text-xs"><span className="text-slate-400">Diamonds</span><b>{25-mineCount}</b></div></BetController>
 return <><GameShell title="Mines" onBack={onBack} panel={panel}><div className="w-full max-w-[590px]"><div className="mb-5 text-center"><div className={`font-display text-4xl font-extrabold ${lost?'text-red-400':'text-lime'}`}>{lost?'BOOM':status==='active'?`${multiplier.toFixed(2)}×`:status==='locked'?'BOARD REVEAL':'Choose your stake'}</div><div className="mt-1 text-xs text-slate-500">{status==='active'?'Find gems, then cash out before the mine.':status==='locked'?'Revealing the full board…':'Configure mines and start a round.'}</div></div><div className="grid grid-cols-5 gap-2 sm:gap-3">{Array.from({length:25},(_,i)=>{const show=revealed.has(i),mine=mines.has(i);return <button aria-label={`Tile ${i+1}`} key={i} onClick={()=>click(i)} className={`tile-shadow aspect-square rounded-lg transition active:translate-y-1 active:shadow-none ${status==='locked'&&show?'mine-reveal ':''}${show?(mine?'bg-red-500':'bg-lime'):'bg-[#2a3b4e] hover:bg-[#344a60]'}`}>{show&&(mine?<Bomb className="mx-auto text-white" size={30}/>:<Gem className="mx-auto text-slate-950" fill="currentColor" size={30}/>)}</button>})}</div></div></GameShell><ResultPopup result={roundResult} onClose={()=>setRoundResult(null)}/></>
}
