import { useEffect, useMemo, useRef, useState } from 'react'
import BetController from '../components/BetController'
import GameShell from '../components/GameShell'
import ResultPopup, { RoundResult } from '../components/ResultPopup'
import { Risk } from '../types'
import { useCasinoWallet } from '../wallet'

const edge:Record<Risk,number>={Low:5.6,Medium:130,High:10000}
function payouts(rows:number,risk:Risk){ return Array.from({length:rows+1},(_,i)=>{const d=Math.abs(i-rows/2)/(rows/2); const top=edge[risk]; const floor=risk==='Low'?0.5:risk==='Medium'?0.3:0.2; return +(floor+(top-floor)*Math.pow(d,risk==='High'?7:risk==='Medium'?5:3)).toFixed(i===0?0:1)}) }
export default function Plinko({onBack}:{onBack:()=>void}){
 const {debit,credit,balance,recordRound}=useCasinoWallet(); const [amount,setAmount]=useState(10); const [rows,setRows]=useState(12); const [risk,setRisk]=useState<Risk>('Medium'); const [ball,setBall]=useState<{x:number;y:number}|null>(null); const [status,setStatus]=useState<'idle'|'locked'>('idle'); const [result,setResult]=useState<string>('Drop a ball to play'); const [roundResult,setRoundResult]=useState<RoundResult|null>(null); const [landingIndex,setLandingIndex]=useState<number|null>(null); const intervalRef=useRef(0); const ballHideRef=useRef(0); const settleRef=useRef(0)
 const bins=useMemo(()=>payouts(rows,risk),[rows,risk]); const pegs=useMemo(()=>Array.from({length:rows},(_,r)=>Array.from({length:r+3},(_,c)=>({x:250+(c-(r+2)/2)*(310/(rows+2)),y:40+r*(315/rows)}))).flat(),[rows])
 const play=()=>{if(status!=='idle'||!debit(amount))return;setRoundResult(null);setLandingIndex(null);setStatus('locked');setResult('Ball in play…');let r=0,x=250;const path:number[]=[];for(let i=0;i<rows;i++){x+=(Math.random()<.5?-1:1)*(155/(rows+1));path.push(x)}setBall({x:250,y:15});intervalRef.current=window.setInterval(()=>{if(r<rows){setBall({x:path[r],y:50+r*(315/rows)});r++}else{clearInterval(intervalRef.current);const idx=Math.max(0,Math.min(rows,Math.round((x-95)/(310/rows))));const multi=bins[idx];const payout=Math.floor(amount*multi);const profit=payout-amount;const binX=92+idx*(316/bins.length)+(Math.max(8,310/bins.length)/2);setBall({x:binX,y:368});setLandingIndex(idx);setResult(`${multi.toLocaleString()}× landed`);ballHideRef.current=window.setTimeout(()=>setBall(null),420);settleRef.current=window.setTimeout(()=>{credit(payout);recordRound(amount,profit);setResult(`${multi.toLocaleString()}× · ⬡ ${payout.toLocaleString()}`);setRoundResult({profit});setStatus('idle')},650)}},135)}
 useEffect(()=>()=>{clearInterval(intervalRef.current);clearTimeout(ballHideRef.current);clearTimeout(settleRef.current)},[])
 const panel=<BetController amount={amount} setAmount={setAmount} status={status} onAction={play} disabled={amount>balance} lastResult={roundResult}>{<><Field label="Risk"><select disabled={status!=='idle'} value={risk} onChange={e=>setRisk(e.target.value as Risk)} className="control"><option>Low</option><option>Medium</option><option>High</option></select></Field><Field label="Rows"><select disabled={status!=='idle'} value={rows} onChange={e=>setRows(Number(e.target.value))} className="control">{Array.from({length:9},(_,i)=><option key={i}>{i+8}</option>)}</select></Field></>}</BetController>
 return <><GameShell title="Plinko" onBack={onBack} panel={panel}><div className="w-full max-w-[650px]"><div className="mb-3 text-center text-sm font-bold text-lime">{result}</div><svg viewBox="0 0 500 410" className="w-full overflow-visible"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{pegs.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={rows>13?3:4} fill="#dbe7f3" opacity=".85"/>)}{ball&&<circle cx={ball.x} cy={ball.y} r="7" fill="#ff456c" filter="url(#glow)" style={{transition:'all 135ms ease-in'}}/>}{bins.map((m,i)=><g key={i} className={landingIndex===i?'bin-hit':''}><rect x={92+i*(316/bins.length)} y="377" width={Math.max(8,310/bins.length)} height="27" rx="3" fill={i===0||i===bins.length-1?'#ff365f':Math.abs(i-bins.length/2)>bins.length*.3?'#ff922f':'#f6d849'}/><text x={97+i*(316/bins.length)} y="394" fill="#101827" fontSize={rows>12?'6':'8'} fontWeight="800">{m}×</text></g>)}</svg></div></GameShell><ResultPopup result={roundResult} onClose={()=>setRoundResult(null)}/></>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-400">{label}</span>{children}</label>}
