import { ReactNode, useEffect, useRef, useState } from 'react'
import { BetStatus } from '../types'
import { useCasinoWallet } from '../wallet'

type Props={amount:number;setAmount:(n:number)=>void;status:BetStatus;onAction:()=>void;onAutoAction?:()=>void;canCashOut?:boolean;disabled?:boolean;children?:ReactNode;potential?:number;autoTarget?:number;setAutoTarget?:(value:number)=>void}
export default function BetController({amount,setAmount,status,onAction,onAutoAction,canCashOut=false,disabled=false,children,potential,autoTarget,setAutoTarget}:Props){
 const {balance}=useCasinoWallet(); const [mode,setMode]=useState<'manual'|'auto'>('manual');const [betCount,setBetCount]=useState(5);const [remaining,setRemaining]=useState(0);const [autoRunning,setAutoRunning]=useState(false);const timer=useRef(0);const label=status==='idle'?'Place bet':canCashOut?'Cash out':'Bet active'
 useEffect(()=>{clearTimeout(timer.current);if(!autoRunning||status!=='idle')return;if(remaining<=0||amount>balance){setAutoRunning(false);return}timer.current=window.setTimeout(()=>{setRemaining(value=>value-1);(onAutoAction||onAction)()},550);return()=>clearTimeout(timer.current)},[autoRunning,status,remaining,amount,balance,onAction,onAutoAction])
 useEffect(()=>()=>clearTimeout(timer.current),[])
 const changeMode=(next:'manual'|'auto')=>{if(autoRunning)return;setMode(next)}
 const toggleAuto=()=>{if(autoRunning){setAutoRunning(false);return}if(status!=='idle'||disabled||amount>balance)return;setRemaining(betCount);setAutoRunning(true)}
 return <aside className="glass w-full shrink-0 rounded-2xl border border-white/5 p-4 lg:w-[300px] lg:rounded-r-none">
  <div className="mb-5 flex rounded-xl bg-[#0d1725] p-1"><button onClick={()=>changeMode('manual')} className={`flex-1 rounded-lg py-2 text-sm font-semibold ${mode==='manual'?'bg-[#26364a] text-white':'text-slate-500'}`}>Manual</button><button onClick={()=>changeMode('auto')} className={`flex-1 rounded-lg py-2 text-sm font-semibold ${mode==='auto'?'bg-[#26364a] text-white':'text-slate-500'}`}>Auto</button></div>
  <label className="mb-2 flex justify-between text-xs font-semibold text-slate-400"><span>Bet amount</span><span>⬡ {amount.toLocaleString()}</span></label>
  <div className="flex overflow-hidden rounded-lg border border-white/5 bg-[#0b1421] focus-within:border-sky-400/50"><div className="flex flex-1 items-center gap-2 px-3"><span className="text-sm font-bold text-lime">⬡</span><input aria-label="Bet amount" disabled={status!=='idle'||autoRunning} type="number" min="1" step="1" value={amount} onChange={e=>setAmount(Math.max(1,Math.floor(Number(e.target.value)||1)))} className="w-full bg-transparent py-3 text-sm font-semibold outline-none"/></div><button disabled={status!=='idle'||autoRunning} onClick={()=>setAmount(Math.max(1,Math.floor(amount/2)))} className="border-l border-white/5 px-3 text-xs font-bold text-slate-300 hover:bg-white/5">½</button><button disabled={status!=='idle'||autoRunning} onClick={()=>setAmount(Math.min(balance,amount*2))} className="border-l border-white/5 px-3 text-xs font-bold text-slate-300 hover:bg-white/5">2×</button></div>
  <div className="my-5 space-y-4">{children}</div>
  {mode==='auto'?<div className="mb-4 space-y-3 rounded-lg bg-[#0c1623] p-3"><label className="block"><span className="mb-2 flex justify-between text-xs font-semibold text-slate-400"><span>Number of bets</span><span>{autoRunning?`${remaining} remaining`:betCount}</span></span><select disabled={autoRunning||status!=='idle'} value={betCount} onChange={event=>setBetCount(Number(event.target.value))} className="control"><option value="5">5 bets</option><option value="10">10 bets</option><option value="25">25 bets</option><option value="100">100 bets</option></select></label>{setAutoTarget&&autoTarget!==undefined?<label className="block"><span className="mb-2 block text-xs font-semibold text-slate-400">Auto cash out</span><div className="flex items-center rounded-lg border border-white/5 bg-[#0b1421] px-3"><input disabled={autoRunning||status!=='idle'} type="number" min="1.01" step=".01" value={autoTarget} onChange={event=>setAutoTarget(Math.max(1.01,Number(event.target.value)||1.01))} className="w-full bg-transparent py-2 font-bold outline-none"/><b className="text-slate-500">×</b></div></label>:null}</div>:null}
  {potential && status==='active'?<div className="mb-3 flex justify-between rounded-lg bg-lime/10 px-3 py-2 text-xs"><span className="text-slate-400">Cashout value</span><b className="text-lime">⬡ {Math.floor(potential).toLocaleString()}</b></div>:null}
  {mode==='manual'?<button onClick={onAction} disabled={disabled||(status!=='idle'&&!canCashOut)} className={`w-full rounded-lg py-3.5 text-sm font-bold transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50 ${canCashOut?'bg-amber-400 text-slate-950 hover:bg-amber-300':'bg-lime text-slate-950 hover:bg-[#c6fa66]'}`}>{label}</button>:<button onClick={toggleAuto} disabled={!autoRunning&&(disabled||status!=='idle')} className={`w-full rounded-lg py-3.5 text-sm font-bold transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50 ${autoRunning?'bg-red-400 text-slate-950 hover:bg-red-300':'bg-lime text-slate-950 hover:bg-[#c6fa66]'}`}>{autoRunning?'Stop auto bet':'Start auto bet'}</button>}
  <div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4 text-[10px] font-semibold uppercase tracking-wider text-slate-500"><span>Demo play</span><span>Provably fair</span></div>
 </aside>
}
