import { GameId } from './types'
import { ArrowRight, Bomb, ChevronRight, CircleDot, Gem, Rocket, Search, Sparkles, Zap } from 'lucide-react'

const games:{id:GameId;name:string;players:number;colors:string;icon:typeof Gem;caption:string}[]=[
 {id:'plinko',name:'Plinko',players:669,colors:'from-fuchsia-600 via-pink-500 to-orange-400',icon:CircleDot,caption:'UP TO 10,000×'},
 {id:'mines',name:'Mines',players:1243,colors:'from-cyan-500 via-blue-600 to-indigo-700',icon:Gem,caption:'FIND THE GEMS'},
 {id:'crash',name:'Crash',players:8204,colors:'from-violet-600 via-fuchsia-600 to-rose-500',icon:Rocket,caption:'CASH OUT IN TIME'},
 {id:'limbo',name:'Limbo',players:426,colors:'from-emerald-500 via-teal-500 to-cyan-600',icon:Zap,caption:'HOW HIGH CAN IT GO?'},
]
const extras=[['Dice','from-red-500 to-orange-400','10,234'],['Keno','from-purple-600 to-indigo-500','728'],['Wheel','from-amber-400 to-red-500','512'],['Dragon Tower','from-emerald-600 to-lime-500','937'],['Blackjack','from-slate-700 to-red-700','2,104'],['Baccarat','from-cyan-700 to-blue-800','369'],['Video Poker','from-orange-600 to-pink-600','744'],['Roulette','from-green-700 to-emerald-500','1,921']]
export default function Lobby({open}:{open:(id:GameId)=>void}){return <main className="mx-auto max-w-[1440px] px-4 pb-16 sm:px-7"><section className="relative mt-5 overflow-hidden rounded-3xl border border-white/5 bg-gradient-to-r from-[#1c3044] to-[#122031] px-7 py-10 sm:px-12 sm:py-14"><div className="noise absolute inset-0"/><div className="relative max-w-xl"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-lime"><Sparkles size={14}/> Originals arcade</div><h1 className="font-display text-4xl font-extrabold leading-tight sm:text-6xl">Small moments.<br/><span className="text-lime">Big multipliers.</span></h1><p className="mt-4 max-w-md text-sm leading-6 text-slate-400">Four instant games, one demo wallet. Every round is simulated locally for a fast, private playground.</p><button onClick={()=>open('plinko')} className="mt-7 flex items-center gap-2 rounded-xl bg-lime px-5 py-3 text-sm font-extrabold text-slate-950">Play Plinko <ArrowRight size={16}/></button></div><div className="absolute -bottom-16 right-[-30px] hidden h-72 w-72 rotate-12 rounded-[60px] bg-gradient-to-br from-fuchsia-500 to-orange-400 shadow-[0_0_90px_rgba(232,77,164,.25)] md:block"><div className="grid h-full place-items-center"><CircleDot size={130} className="text-white/90"/></div></div></section><Section title="Obsidian Originals"><div className="grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-4">{games.map(g=><GameCard key={g.id} {...g} onClick={()=>open(g.id)}/>)}</div></Section><Section title="More games"><div className="grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-6">{extras.map(([name,color,players],i)=><button key={name} className="game-card overflow-hidden rounded-xl text-left"><div className={`card-art relative aspect-[4/5] overflow-hidden rounded-xl bg-gradient-to-br ${color}`}><div className="noise absolute inset-0"/><div className="absolute inset-0 grid place-items-center text-white/85">{i%2?<Bomb size={52}/>:<Sparkles size={52}/>}</div><span className="absolute bottom-3 left-3 rounded bg-black/30 px-2 py-1 text-[9px] font-bold uppercase">Coming soon</span></div><h3 className="mt-2 text-sm font-bold">{name}</h3><p className="mt-0.5 text-[11px] text-slate-500"><span className="text-emerald-400">●</span> {players} playing</p></button>)}</div></Section></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-10"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-extrabold">{title}</h2><button className="flex items-center text-xs font-bold text-slate-500">View all <ChevronRight size={15}/></button></div>{children}</section>}
function GameCard({name,players,colors,icon:Icon,caption,onClick}:{name:string;players:number;colors:string;icon:typeof Gem;caption:string;onClick:()=>void}){return <button onClick={onClick} className="game-card text-left"><div className={`card-art relative aspect-[4/5] overflow-hidden rounded-xl bg-gradient-to-br ${colors} shadow-lg shadow-black/20`}><div className="noise absolute inset-0"/><div className="absolute inset-x-0 top-7 text-center text-[10px] font-black tracking-[.24em] text-white/70">{caption}</div><div className="absolute inset-0 grid place-items-center"><div className="grid h-28 w-28 rotate-6 place-items-center rounded-[32px] bg-black/15 shadow-2xl backdrop-blur-sm"><Icon size={68} strokeWidth={2.4} className="text-white"/></div></div><span className="absolute bottom-3 left-3 rounded bg-black/30 px-2 py-1 text-[9px] font-bold uppercase backdrop-blur">Obsidian Original</span></div><h3 className="mt-2.5 text-sm font-bold">{name}</h3><p className="mt-0.5 text-[11px] text-slate-500"><span className="text-emerald-400">●</span> {players.toLocaleString()} playing</p></button>}
